---
title: "Take-home Exercise 2"
author: "CHJ1"
date: "October 18, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

Loading the package

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse, knitr, dplyr)
```

Preparing the Data

```{r}
mpsz = read_rds("data/rds/mpsz_sf.rds")
```

```{r}
BusStop = st_read(dsn = "data/Geospatial/",
                  layer = "BusStop") %>%
  st_transform(crs = 3414)
```

```{r}
odbus <- read_csv("data/LTADataMall/origin_destination_bus_202508.csv")
```

```{r}
tm_shape(mpsz) +
  tm_polygons() +
tm_shape(BusStop) +
  tm_dots()
```

```{r}
BusStop_in_SG <- st_join(
  BusStop, mpsz,
  join = st_within,
  left = FALSE)
```

```{r}
tm_shape(mpsz) +
  tm_polygons() +
tm_shape(BusStop_in_SG) +
  tm_dots()
```

```{r}
hexagon <- st_make_grid(mpsz,
                        cellsize = 750,
                        what = "polygon",
                        square = FALSE) %>%
  st_sf()
```

```{r}
hexagon$n_collisions = 
  lengths(st_intersects(
    hexagon, BusStop_in_SG))

hexagon <- filter(hexagon, n_collisions > 0)
```

```{r}
hexagon <- hexagon %>%
  select(, -n_collisions)

hexagon$HEX_ID <- sprintf(
  "H%04d", seq_len(nrow(hexagon))) %>%
  as.factor()
    
kable(head(hexagon))
```

```{r}
trips <- odbus %>%
  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%
  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%
  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%
  rename(TRIPS = TOTAL_TRIPS)
trips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)
kable(head(trips))
```

```{r}
bs_hex <- st_intersection(
  BusStop, hexagon) %>%
  st_drop_geometry() %>%
  select(c(BUS_STOP_N, HEX_ID))
kable(head(bs_hex))
```

```{r}
trips <- inner_join(trips, bs_hex)
kable(head(trips))
```

```{r}
# Weekday morning peak trips (6am-9am)
weekday_morning_peak <- trips %>%
  filter(DAY_TYPE == "WEEKDAY",
         HOUR_OF_DAY >= 6, HOUR_OF_DAY <= 9) %>%
  group_by(HEX_ID) %>%
  summarise(TRIPS_MORNING_PEAK = sum(TRIPS))
```

```{r}
# Weekday afternoon peak trips (5pm-8pm)
weekday_afternoon_peak <- trips %>%
  filter(DAY_TYPE == "WEEKDAY",
         HOUR_OF_DAY >= 17, HOUR_OF_DAY <= 20) %>%
  group_by(HEX_ID) %>%
  summarise(TRIPS_AFTERNOON_PEAK = sum(TRIPS))
```

```{r}
# Weekend/holiday trips (11am-8pm)
weekend_holiday_peak <- trips %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY",
         HOUR_OF_DAY >= 11, HOUR_OF_DAY <= 20) %>%
  group_by(HEX_ID) %>%
  summarise(TRIPS_WEEKEND_HOLIDAY = sum(TRIPS))
```

```{r}
# Combine results
trips_by_peak <- full_join(weekday_morning_peak, weekday_afternoon_peak, by = "HEX_ID") %>%
  full_join(weekend_holiday_peak, by = "HEX_ID") %>%
  replace_na(list(
    TRIPS_MORNING_PEAK = 0,
    TRIPS_AFTERNOON_PEAK = 0,
    TRIPS_WEEKEND_HOLIDAY = 0))

print(trips_by_peak)
```

```{r}
trips_by_hex <- trips %>%
  group_by(HEX_ID) %>%
  summarise(TOTAL_TRIPS = sum(TRIPS))
```

```{r}
hexagon_trips <- hexagon %>%
  left_join(trips_by_hex, by = "HEX_ID") %>%
  replace_na(list(TOTAL_TRIPS = 0))
```

```{r}
tm_shape(hexagon_trips) +
  tm_polygons("TOTAL_TRIPS",
              palette = "Reds",
              title = "Passenger Trips",
              style = "quantile") +
  tm_shape(BusStop_in_SG) +
  tm_dots(size = 0.1, col = "blue") +
  tm_layout(title = "Geographical Distribution of Passenger Trips by TAZ")
```
