---
title: "Take-home Exercise 1"
author: "CHJ1"
date: "September 13, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse, sf, tmap, httr, rvest, spatstat)
```

```{r}
folder_path <- "data"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names = TRUE)

acra_data <- file_list %>%
  map_dfr(read_csv)
```

```{r}
#|eval: false
#|echo: false
write_rds(acra_data,
          "data/acra_data.rds")
```

```{r}
biz_56111_55101_56130 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code %in% c(56111, 55101, 56130)) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM = month(date),
         MONTH_ABBR = month(date,
                      label = TRUE,
                      abbr = TRUE)) %>%
  mutate( 
    postal_code = str_pad(postal_code,
    width = 6, side = "left", pad = "0")) %>%
           filter(YEAR == 2025)
```

```{r}
postcodes <- unique(biz_56111_55101_56130$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"

found <- data.frame()
not_found <- data.frame(postcode = character())

for (pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "Y",
    pageNum = "1"
  )
  
  res <- GET(url, query = query)
  json <- content(res)
  
  if (json$found != 0) {
    df <- as.data.frame(json$results, stringsAsFactors = FALSE)
    df$input_postcode <- pc
    found <- bind_rows(found, df)
  } else {
    not_found <- bind_rows(not_found, data.frame(postcode = pc))
  }
}    
```

```{r}
found <- found %>%
  select(1:10)
```

```{r}
biz_56111_55101_56130 = biz_56111_55101_56130 %>%
  left_join(found,
            by = c('postal_code' = 'POSTAL'))
```

```{r}
write_rds(biz_56111_55101_56130, "data/biz_56111_55101_56130.rds")
```

```{r}
biz_56111_55101_56130_sf <- st_as_sf(biz_56111_55101_56130, 
                         coords = c("X","Y"),
                         crs=3414) 
```

```{r}
ggplot(data = biz_56111_55101_56130,
       aes(x = MONTH_ABBR)) +
  geom_bar()
```

```{r}
tmap_mode('view')
tm_shape(biz_56111_55101_56130_sf)+
  tm_dots()
```

```{r}
biz_56111_55101_56130_sf_firsthalf2025 <- biz_56111_55101_56130_sf %>%
  filter(YEAR == 2025, MONTH_NUM %in% 1:6)
```

```{r}
split_list <- split(biz_56111_55101_56130_sf_firsthalf2025, 
                    biz_56111_55101_56130_sf_firsthalf2025$primary_ssic_code)

biz_56111_sf_firsthalf2025 <- split_list[["56111"]]
biz_55101_sf_firsthalf2025 <- split_list[["55101"]]
biz_56130_sf_firsthalf2025 <- split_list[["56130"]]
```

```{r}
mpsz = st_read(dsn = "data", 
                  layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
plot(mpsz)
```

```{r}
st_crs(mpsz)
mpsz <- st_set_crs(mpsz, 3414)
```

```{r}
plot(st_geometry(mpsz))
plot(st_geometry(biz_56111_sf_firsthalf2025), add = TRUE)
```

```{r}
plot(st_geometry(mpsz))
plot(st_geometry(biz_55101_sf_firsthalf2025), add = TRUE)
```

```{r}
plot(st_geometry(mpsz))
plot(st_geometry(biz_56130_sf_firsthalf2025), add = TRUE)
```

```{r}
mpsz$`biz_56111_sf_firsthalf2025`<- lengths(st_intersects(mpsz, biz_56111_sf_firsthalf2025))
summary(mpsz$`biz_56111_sf_firsthalf2025`)

top_n(mpsz, 1, `biz_56111_sf_firsthalf2025`)
```

```{r}
mpsz$Area <- mpsz %>%
  st_area()
```

```{r}
mpsz <- mpsz %>%
  mutate(`biz_56111_sf_firsthalf2025 Density` = `biz_56111_sf_firsthalf2025`/Area * 1000000)

hist(mpsz$`biz_56111_sf_firsthalf2025 Density`)
```

```{r}
ggplot(data=mpsz, 
       aes(y = `biz_56111_sf_firsthalf2025`, 
           x= as.numeric(`biz_56111_sf_firsthalf2025 Density`)))+
  geom_point(color="black", 
             fill="light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(title = "",
      x = "biz_56111_sf_firsthalf2025 density (per km sq)",
      y = "biz_56111_sf_firsthalf2025 count")
```

```{r}
mpsz$`biz_55101_sf_firsthalf2025`<- lengths(st_intersects(mpsz, biz_55101_sf_firsthalf2025))
summary(mpsz$`biz_55101_sf_firsthalf2025`)

top_n(mpsz, 1, `biz_55101_sf_firsthalf2025`)
```

```{r}
mpsz <- mpsz %>%
  mutate(`biz_55101_sf_firsthalf2025 Density` = `biz_55101_sf_firsthalf2025`/Area * 1000000)

hist(mpsz$`biz_55101_sf_firsthalf2025 Density`)
```

```{r}
ggplot(data=mpsz, 
       aes(y = `biz_55101_sf_firsthalf2025`, 
           x= as.numeric(`biz_55101_sf_firsthalf2025 Density`)))+
  geom_point(color="black", 
             fill="light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(title = "",
      x = "biz_55101_sf_firsthalf2025 density (per km sq)",
      y = "biz_55101_sf_firsthalf2025 count")
```

```{r}
mpsz$`biz_56130_sf_firsthalf2025`<- lengths(st_intersects(mpsz, biz_56130_sf_firsthalf2025))
summary(mpsz$`biz_56130_sf_firsthalf2025`)

top_n(mpsz, 1, `biz_56130_sf_firsthalf2025`)
```

```{r}
mpsz <- mpsz %>%
  mutate(`biz_56130_sf_firsthalf2025 Density` = `biz_56130_sf_firsthalf2025`/Area * 1000000)

hist(mpsz$`biz_56130_sf_firsthalf2025 Density`)
```

```{r}
ggplot(data=mpsz, 
       aes(y = `biz_56130_sf_firsthalf2025`, 
           x= as.numeric(`biz_56130_sf_firsthalf2025 Density`)))+
  geom_point(color="black", 
             fill="light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(title = "",
      x = "biz_56130_sf_firsthalf2025 density (per km sq)",
      y = "biz_56130_sf_firsthalf2025 count")
```

```{r}
extract_kml_field <- function(html_text, field_name) {
  if (is.na(html_text) || html_text == "") return(NA_character_)
  
  page <- read_html(html_text)
  rows <- page %>% html_elements("tr")
  
  value <- rows %>%
    keep(~ html_text2(html_element(.x, "th")) == field_name) %>%
    html_element("td") %>%
    html_text2()
  
  if (length(value) == 0) NA_character_ else value
}
```

```{r}
mpsz2 <- st_read("data/MasterPlan2019SubzoneBoundaryNoSeaKML.kml") %>% 
  st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 3414)
```

```{r}
mpsz2 <- mpsz2 %>%
  mutate(
    REGION_N = map_chr(Description, extract_kml_field, "REGION_N"),
    PLN_AREA_N = map_chr(Description, extract_kml_field, "PLN_AREA_N"),
    SUBZONE_N = map_chr(Description, extract_kml_field, "SUBZONE_N"),
    SUBZONE_C = map_chr(Description, extract_kml_field, "SUBZONE_C")
  ) %>%
  select(-Name, -Description) %>%
  relocate(geometry, .after = last_col())
```

```{r}
mpsz_cl <- mpsz2 %>%
  filter(SUBZONE_N != "SOUTHERN GROUP",
         PLN_AREA_N != "WESTERN ISLANDS",
         PLN_AREA_N != "NORTH-EASTERN ISLANDS")
```

```{r}
write_rds(mpsz_cl, 
          "data/mpsz_cl.rds")
```

```{r}
sg_owin <- as.owin(mpsz_cl)
```

```{r}
biz_56111_sf_firsthalf2025_ppp <- as.ppp(biz_56111_sf_firsthalf2025)
biz_56111_sf_firsthalf2025SG_ppp = biz_56111_sf_firsthalf2025_ppp[sg_owin]
```

```{r}
biz_55101_sf_firsthalf2025_ppp <- as.ppp(biz_55101_sf_firsthalf2025)
biz_55101_sf_firsthalf2025SG_ppp = biz_55101_sf_firsthalf2025_ppp[sg_owin]
```

```{r}
biz_56130_sf_firsthalf2025_ppp <- as.ppp(biz_56130_sf_firsthalf2025)
biz_56130_sf_firsthalf2025SG_ppp = biz_56130_sf_firsthalf2025_ppp[sg_owin]
```

```{r}
clarkevans.test(biz_56111_sf_firsthalf2025SG_ppp,
                correction="none",
                clipregion="sg_owin",
                alternative=c("clustered"),
                method="MonteCarlo",
                nsim=99)
```

```{r}
clarkevans.test(biz_55101_sf_firsthalf2025SG_ppp,
                correction="none",
                clipregion="sg_owin",
                alternative=c("clustered"),
                method="MonteCarlo",
                nsim=99)
```

```{r}
clarkevans.test(biz_56130_sf_firsthalf2025SG_ppp,
                correction="none",
                clipregion="sg_owin",
                alternative=c("clustered"),
                method="MonteCarlo",
                nsim=99)
```

```{r}
biz_56111_sf_firsthalf2025SG_ppp_km <- rescale.ppp(
  biz_56111_sf_firsthalf2025SG_ppp, 1000, "km")
  
kde_biz_56111_sf_firsthalf2025SG_ppp_km <- density(biz_56111_sf_firsthalf2025SG_ppp_km,
                              sigma=bw.diggle,
                              edge=TRUE,
                              kernel="gaussian")
  
plot(kde_biz_56111_sf_firsthalf2025SG_ppp_km)
```
  
```{r}
biz_55101_sf_firsthalf2025SG_ppp_km <- rescale.ppp(
  biz_55101_sf_firsthalf2025SG_ppp, 1000, "km")
  
kde_biz_55101_sf_firsthalf2025SG_ppp_km <- density(biz_55101_sf_firsthalf2025SG_ppp_km,
                              sigma=bw.diggle,
                              edge=TRUE,
                              kernel="gaussian")
  
plot(kde_biz_55101_sf_firsthalf2025SG_ppp_km)
```

```{r}
biz_56130_sf_firsthalf2025SG_ppp_km <- rescale.ppp(
  biz_56130_sf_firsthalf2025SG_ppp, 1000, "km")
  
kde_biz_56130_sf_firsthalf2025SG_ppp_km <- density(biz_56130_sf_firsthalf2025SG_ppp_km,
                              sigma=bw.diggle,
                              edge=TRUE,
                              kernel="gaussian")
  
plot(kde_biz_56130_sf_firsthalf2025SG_ppp_km)
```

```{r}
set.seed(1234)
```
  
  
